import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 
          Main container wrapper - applies to ALL pages in your app
          This provides consistent padding and max-width across all pages
          
          You can modify these Tailwind classes:
          - min-h-screen: Ensures the container takes up at least full viewport height
          - px-4: Horizontal padding (1rem / 16px on mobile)
          - py-8: Vertical padding (2rem / 32px top and bottom)
          - max-w-7xl: Maximum width of 80rem / 1280px (prevents content from being too wide)
          - mx-auto: Centers the container horizontally
          
          To change padding: adjust px-4 and py-8 (e.g., px-6, py-12 for more spacing)
          To change max width: use max-w-5xl, max-w-6xl, max-w-full, etc.
        */}
        <div className="min-h-screen px-5 py-5 max-w-8xl mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
